module br {
	module furb {	
		module corba {
			module compra {
				interface Produto {
					double getValorUnitario();
					void setValorUnitario(in double valorUnitario);
					long getCodigoProduto();
					void setCodigoProduto(in long codigoProduto);
					string getDescricaoProduto();
					void setDescricaoProduto(in string descricaoProduto);
					long getQtdProduto();		
					void setQtdProduto(in long qtdProduto);	
					string toString();		
				};		
			
				interface Compra {
				    boolean recebeNota(in Produto produto);
				    void updateServerTime();
				    long long getServerTime();
				    void setServerTime(in long long localTime);
				};									
			};
		};
	};
};
