module br {
	module furb {	
		module corba {
			module compra {
				interface Compra {
				    boolean recebeNota(in long aCodigo, in string aNome, in long aQuantidade, in double aValorUnitario);
				    void updateServerTime();
				    long long getServerTime();
				    void setServerTime(in long long localTime);
				};									
			};
		};
	};
};
