package br.furb.corba.compra;


/**
* br/furb/corba/compra/Compra.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Compra.idl
* Sábado, 21 de Maio de 2016 16h49min29s BRT
*/

public interface Compra extends CompraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Compra
