package br.furb.corba.compra;


/**
* br/furb/corba/compra/CompraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from br/furb/corba/Compra.idl
* Segunda-feira, 23 de Maio de 2016 22h43min32s BRT
*/

public interface CompraOperations 
{
  boolean recebeNota (br.furb.corba.compra.Produto produto);
  void updateServerTime ();
  long getServerTime ();
  void setServerTime (long localTime);
} // interface CompraOperations
