package br.furb.corba.compra;

/**
* br/furb/corba/compra/CompraHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from br/furb/corba/Compra.idl
* Quinta-feira, 26 de Maio de 2016 11h32min34s BRT
*/

public final class CompraHolder implements org.omg.CORBA.portable.Streamable
{
  public br.furb.corba.compra.Compra value = null;

  public CompraHolder ()
  {
  }

  public CompraHolder (br.furb.corba.compra.Compra initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.furb.corba.compra.CompraHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.furb.corba.compra.CompraHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.furb.corba.compra.CompraHelper.type ();
  }

}
