package br.furb.corba.compra;


/**
* br/furb/corba/compra/Compra.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from br/furb/corba/Compra.idl
* Quinta-feira, 26 de Maio de 2016 11h32min34s BRT
*/

public interface Compra extends CompraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Compra
