package br.furb.corba.compra;


/**
* br/furb/corba/compra/CompraPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Compra.idl
* Domingo, 22 de Maio de 2016 16h24min12s BRT
*/

public abstract class CompraPOA extends org.omg.PortableServer.Servant
 implements br.furb.corba.compra.CompraOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("recebeNota", new java.lang.Integer (0));
    _methods.put ("comunicaEstoque", new java.lang.Integer (1));
    _methods.put ("updateServerTime", new java.lang.Integer (2));
    _methods.put ("getServerTime", new java.lang.Integer (3));
    _methods.put ("setServerTime", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // br/furb/corba/compra/Compra/recebeNota
       {
         boolean $result = false;
         $result = this.recebeNota ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // br/furb/corba/compra/Compra/comunicaEstoque
       {
         boolean $result = false;
         $result = this.comunicaEstoque ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // br/furb/corba/compra/Compra/updateServerTime
       {
         this.updateServerTime ();
         out = $rh.createReply();
         break;
       }

       case 3:  // br/furb/corba/compra/Compra/getServerTime
       {
         long $result = (long)0;
         $result = this.getServerTime ();
         out = $rh.createReply();
         out.write_longlong ($result);
         break;
       }

       case 4:  // br/furb/corba/compra/Compra/setServerTime
       {
         long localTime = in.read_longlong ();
         this.setServerTime (localTime);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/furb/corba/compra/Compra:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Compra _this() 
  {
    return CompraHelper.narrow(
    super._this_object());
  }

  public Compra _this(org.omg.CORBA.ORB orb) 
  {
    return CompraHelper.narrow(
    super._this_object(orb));
  }


} // class CompraPOA
