package br.furb.corba.compra;


/**
* br/furb/corba/compra/ProdutoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from br/furb/corba/Compra.idl
* Segunda-feira, 23 de Maio de 2016 22h43min32s BRT
*/

public interface ProdutoOperations 
{
  double getValorUnitario ();
  void setValorUnitario (double valorUnitario);
  int getCodigoProduto ();
  void setCodigoProduto (int codigoProduto);
  String getDescricaoProduto ();
  void setDescricaoProduto (String descricaoProduto);
  int getQtdProduto ();
  void setQtdProduto (int qtdProduto);
  String _toString ();
} // interface ProdutoOperations
