package br.furb.corba.compra;


/**
* br/furb/corba/compra/ProdutoHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from br/furb/corba/Compra.idl
* Segunda-feira, 23 de Maio de 2016 22h43min32s BRT
*/

abstract public class ProdutoHelper
{
  private static String  _id = "IDL:br/furb/corba/compra/Produto:1.0";

  public static void insert (org.omg.CORBA.Any a, br.furb.corba.compra.Produto that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static br.furb.corba.compra.Produto extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (br.furb.corba.compra.ProdutoHelper.id (), "Produto");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static br.furb.corba.compra.Produto read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ProdutoStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, br.furb.corba.compra.Produto value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static br.furb.corba.compra.Produto narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof br.furb.corba.compra.Produto)
      return (br.furb.corba.compra.Produto)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      br.furb.corba.compra._ProdutoStub stub = new br.furb.corba.compra._ProdutoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static br.furb.corba.compra.Produto unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof br.furb.corba.compra.Produto)
      return (br.furb.corba.compra.Produto)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      br.furb.corba.compra._ProdutoStub stub = new br.furb.corba.compra._ProdutoStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
