package br.furb.corba.compra;


/**
* br/furb/corba/compra/ProdutoPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from br/furb/corba/Compra.idl
* Segunda-feira, 23 de Maio de 2016 22h43min32s BRT
*/

public abstract class ProdutoPOA extends org.omg.PortableServer.Servant
 implements br.furb.corba.compra.ProdutoOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getValorUnitario", new java.lang.Integer (0));
    _methods.put ("setValorUnitario", new java.lang.Integer (1));
    _methods.put ("getCodigoProduto", new java.lang.Integer (2));
    _methods.put ("setCodigoProduto", new java.lang.Integer (3));
    _methods.put ("getDescricaoProduto", new java.lang.Integer (4));
    _methods.put ("setDescricaoProduto", new java.lang.Integer (5));
    _methods.put ("getQtdProduto", new java.lang.Integer (6));
    _methods.put ("setQtdProduto", new java.lang.Integer (7));
    _methods.put ("toString", new java.lang.Integer (8));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // br/furb/corba/compra/Produto/getValorUnitario
       {
         double $result = (double)0;
         $result = this.getValorUnitario ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       case 1:  // br/furb/corba/compra/Produto/setValorUnitario
       {
         double valorUnitario = in.read_double ();
         this.setValorUnitario (valorUnitario);
         out = $rh.createReply();
         break;
       }

       case 2:  // br/furb/corba/compra/Produto/getCodigoProduto
       {
         int $result = (int)0;
         $result = this.getCodigoProduto ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // br/furb/corba/compra/Produto/setCodigoProduto
       {
         int codigoProduto = in.read_long ();
         this.setCodigoProduto (codigoProduto);
         out = $rh.createReply();
         break;
       }

       case 4:  // br/furb/corba/compra/Produto/getDescricaoProduto
       {
         String $result = null;
         $result = this.getDescricaoProduto ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // br/furb/corba/compra/Produto/setDescricaoProduto
       {
         String descricaoProduto = in.read_string ();
         this.setDescricaoProduto (descricaoProduto);
         out = $rh.createReply();
         break;
       }

       case 6:  // br/furb/corba/compra/Produto/getQtdProduto
       {
         int $result = (int)0;
         $result = this.getQtdProduto ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 7:  // br/furb/corba/compra/Produto/setQtdProduto
       {
         int qtdProduto = in.read_long ();
         this.setQtdProduto (qtdProduto);
         out = $rh.createReply();
         break;
       }

       case 8:  // br/furb/corba/compra/Produto/_toString
       {
         String $result = null;
         $result = this._toString ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:br/furb/corba/compra/Produto:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Produto _this() 
  {
    return ProdutoHelper.narrow(
    super._this_object());
  }

  public Produto _this(org.omg.CORBA.ORB orb) 
  {
    return ProdutoHelper.narrow(
    super._this_object(orb));
  }


} // class ProdutoPOA
