package br.furb.corba.compra;

/**
* br/furb/corba/compra/ProdutoHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from br/furb/corba/Compra.idl
* Segunda-feira, 23 de Maio de 2016 22h43min32s BRT
*/

public final class ProdutoHolder implements org.omg.CORBA.portable.Streamable
{
  public br.furb.corba.compra.Produto value = null;

  public ProdutoHolder ()
  {
  }

  public ProdutoHolder (br.furb.corba.compra.Produto initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = br.furb.corba.compra.ProdutoHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    br.furb.corba.compra.ProdutoHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return br.furb.corba.compra.ProdutoHelper.type ();
  }

}
