package br.furb.corba.compra;


/**
* br/furb/corba/compra/Produto.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from br/furb/corba/Compra.idl
* Segunda-feira, 23 de Maio de 2016 22h43min32s BRT
*/

public interface Produto extends ProdutoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Produto
